[package]
name = "uefi_app_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
uefi = { version = "0.34.0", features = ["alloc", "logger", "panic_handler", "global_allocator"] }
x86 = { version = "0.52.0" }
x86_64 = { version = "0.14.11" }
