# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
channel = "nightly-2025-02-22" # 1.77
components = [ "rust-std", "rust-src", "rustc", "cargo", "clippy", "rustfmt" ]
targets = ["aarch64-unknown-uefi", "i686-unknown-uefi", "x86_64-unknown-uefi"]
